### ISSUE TITLE
QucsatorRF developement roadmap

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucsator_rf#1]
Qucsator is a former built-in engine of Qucs. It contains some unique simulation features for RF domain that are hard to implement in the Ngspice. However Qucsator has a very poor time domain performance and not recommended for simulation of general purpose circuits. In the long perspective adding new microwave devices is considered. 

I decided to create this fork in order to bring some new features to Qucsator and keep this simulation kernel alive. The name *Qucsator-RF* indicates that it will be targeted to RF simulation. My intention is to use Qucsator-RF as the supplementary simulation kernel for Qucs-S for RF and microwave circuits analysis. Here is the roadmap for the first release:

- [x] Deprecate Autotools build system and compeltely switch to CMake; remove related Autotools stuff
- [x] Make ADMS dependency optional; in the long perspective it will be needed to switch to OpenVAF OSDI interface 
- [x] Make build `libqucsator.so` optional
- [x] Prepare Windows binary package
- [x] Integrate this repository into the Qucs-S repository using git submodule
- [x] Add the unaccepted patch: https://github.com/Qucs/qucsator/pull/33 by @michal777
- [x] Add the patch: https://github.com/Qucs/qucsator/pull/27 by @thliebig 
- [x] Setup CI using Github workflow

**Comment by ra3xdh** [comment]
Closing as completed.
